import assert from "node:assert/strict";
import test from "node:test";
import { deriveStudentProgress } from "../dist/progress.js";

test("Student Progress derives class-scoped factual attendance and exact raw-score summaries", () => {
  const student = { id: "student-a", fullName: "<script>alert(1)</script> & A" };
  const output = deriveStudentProgress({ student, classId: "class-a", attendance: [{ classId: "class-a", studentId: "student-a", date: "2026-09-03", status: "present" }, { classId: "class-a", studentId: "student-a", date: "2026-09-02", status: "late" }, { classId: "class-a", studentId: "student-a", date: "2026-09-01", status: "absent" }, { classId: "class-a", studentId: "student-a", date: "2026-08-31", status: "excused" }, { classId: "class-a", studentId: "student-b", date: "2026-09-03", status: "present" }], assessments: [{ id: "one", classId: "class-a", title: "Quiz", date: "2026-09-02", maximumScore: "20" }, { id: "two", classId: "class-a", title: "Task", date: "2026-09-01", maximumScore: "10" }, { id: "other", classId: "class-b", title: "Other", date: "2026-09-01", maximumScore: "10" }], scores: [{ assessmentId: "one", classId: "class-a", studentId: "student-a", rawScore: "0" }, { assessmentId: "two", classId: "class-a", studentId: "student-b", rawScore: "10" }] });
  assert.deepEqual(output.attendanceSummary.counts, { present: 1, absent: 1, late: 1, excused: 1 }); assert.equal(output.attendanceSummary.attendanceRate, "50%"); assert.equal(output.assessments.length, 2); assert.equal(output.assessments[0].entered, true); assert.equal(output.assessments[0].rawScore, "0"); assert.equal(output.assessments[0].percentage.display, "0%"); assert.equal(output.assessments[1].entered, false); assert.equal(output.scoreSummary.aggregate.display, "0%");
});

test("Student Progress has no cached ghosts and remains practical for realistic class history", () => {
  const students = Array.from({ length: 100 }, (_, index) => ({ id: `student-${index}`, fullName: `Student ${index}` })); const assessments = Array.from({ length: 40 }, (_, index) => ({ id: `assessment-${index}`, classId: "class", title: `Assessment ${index}`, date: `2026-09-${String((index % 28) + 1).padStart(2, "0")}`, maximumScore: index === 0 ? "25" : "20" })); const attendance = Array.from({ length: 60 * 100 }, (_, index) => ({ classId: "class", studentId: `student-${index % 100}`, date: `2026-08-${String(Math.floor(index / 100) % 28 + 1).padStart(2, "0")}`, status: ["present", "absent", "late", "excused"][index % 4] })); const scores = assessments.map((assessment, index) => ({ assessmentId: assessment.id, classId: "class", studentId: "student-0", rawScore: index === 1 ? "0" : "10" })); const started = performance.now(); const output = deriveStudentProgress({ student: students[0], classId: "class", attendance, assessments, scores }); assert.equal(output.assessments.length, 40); assert.equal(output.assessments.find((item) => item.assessmentId === "assessment-1").rawScore, "0"); assert.equal(output.scoreSummary.aggregate.display, "48.45%"); assert.ok(performance.now() - started < 300, "derived progress should remain responsive");
  const changedMaximum = deriveStudentProgress({ student: students[0], classId: "class", attendance: [], assessments: [{ ...assessments[0], maximumScore: "20" }], scores: [scores[0]] }); assert.equal(changedMaximum.assessments[0].percentage.display, "50%"); const deletedAssessment = deriveStudentProgress({ student: students[0], classId: "class", attendance: [], assessments: [], scores }); assert.equal(deletedAssessment.assessments.length, 0);
});
